BloggerBlogBundle_accueil:
    pattern:  /
    defaults: { _controller: BloggerBlogBundle:Page:accueil }

BloggerBlogBundle_contact:
    pattern:  /contact/
    defaults: { _controller: BloggerBlogBundle:Page:contact }

BloggerBlogBundle_about:
    pattern:  /about/
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        _method:  GET

BloggerBlogBundle_home:
    pattern:  /blog/
    defaults: { _controller: BloggerBlogBundle:Page:index }

BloggerBlogBundle_blog_show:
    pattern:  /blog/{id}/
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    requirements:
        _method: GET
        id: \d+

BloggerBlogBundle_comment_create:
    pattern:  blog/comment/{blog_id}/
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+